### PR TITLE
added native windows mingw build.

### PR DESCRIPTION
**Pull request by dsm**
Hi @ra3xdh, This PR added native windows mingw build support and some improvements.

### CODE REVIEW

**Comment by dsm** [comment]
Hi @ra3xdh, can you check changes ?

**Comment by ra3xdh** [comment]
Merged.

**Comment by ra3xdh** [comment]
@dsm, Something went wrong after merging. The MacOS intel task even cannot start. I have tried restarting several times. 
image

**Comment by dsm** [comment]
can you update macos-12 to macos-13 please

**Comment by dsm** [comment]
btw recently github action stopped I think they used cloudflare.

**Pull request merged**
